package com.andres_lasso.previmed.controller.pacientes.recycler

class BeneficiariosProvider {
    companion object{
        val beneficiariosList = listOf<BeneficiariosClass>(
            BeneficiariosClass(
                "1",
                "Jorge",
                "Porras"
            ),
            BeneficiariosClass(
                "2",
                "Jeison",
                "Reyes"
            ),
            BeneficiariosClass(
                "3",
                "Jesus",
                "Mosquera"
            ),
            BeneficiariosClass(
                "4",
                "Miguel",
                "Patiño"
            ),
            BeneficiariosClass(
                "5",
                "Daniela",
                "Usuga"
            ),
            BeneficiariosClass(
                "6",
                "Amaranta",
                "Hank"
            ),
            BeneficiariosClass(
                "7",
                "Esperanza",
                "Gomez"
            ),
            BeneficiariosClass(
                "8",
                "Cristian",
                "Sandoval"
            ),
            BeneficiariosClass(
                "9",
                "Lenny",
                "Perez"
            ),
            BeneficiariosClass(
                "10",
                "Lida",
                "Vidal"
            ),
            BeneficiariosClass(
                "11",
                "Mauricio",
                "Vega"
            ),
            BeneficiariosClass(
                "12",
                "Oscar",
                "Vega"
            ),
            BeneficiariosClass(
                "13",
                "Camilo",
                "Gomez"
            ),
            BeneficiariosClass(
                "14",
                "Luisa",
                "Fernandez"
            ),
            BeneficiariosClass(
                "15",
                "Mil",
                "House"
            ),
        )
    }
}